### PR TITLE
Service and axiomatic command

### LINKED ISSUE #1: Implement a service
There's a resource, but no service actually exposing this over HTTP. Add one.

### PR DESCRIPTION
**Pull request by mithrandi**
Fixes #1.

[Review on Reviewable](https://reviewable.io/reviews/fusionapp/fusion-index/3)

### CODE REVIEW

**Comment by jonathanj** [comment]
I can't help but notice that there is no Eliot logging here, past experience has shown that having this logging can be incredibly useful. Is there a particular reason logging was omitted entirely?

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[fusion_index/service.py, line 129 \[r1\]](https://reviewable.io:443/reviews/fusionapp/fusion-index/3#-JzVqg1zDc9DNfBnOy6k)** ([raw file](https://github.com/fusionapp/fusion-index/blob/04c5e97e1511b30b457d609cfd9ec7eb95e4971a/fusion_index/service.py#L129)):</sup>
The docstring here indicates this command has inspection capabilities but there is no code for the "you didn't pass the create flag but a service exists, here's what it looks like" case.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/fusion-index/3)

**Comment by mithrandi** [comment]
No, that's a good idea. I was waiting until I had a logging service hooked up, but I guess that isn't actually a prerequisite at all. I add some eliot logging to service start/stop, as well as to the backend; let me know if there's anything you think I missed.

---

Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[fusion_index/service.py, line 129 \[r1\]](https://reviewable.io:443/reviews/fusionapp/fusion-index/3#-JzVqg1zDc9DNfBnOy6k)** ([raw file](https://github.com/fusionapp/fusion-index/blob/04c5e97e1511b30b457d609cfd9ec7eb95e4971a/fusion_index/service.py#L129)):</sup>
Oops, I didn't actually finish this code (it also doesn't apply any modifications if the service already exists). I've fixed that now.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/fusion-index/3)

**Comment by jonathanj** [comment]
Reviewed 5 of 7 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[fusion_index/logging.py, line 9 \[r3\]](https://reviewable.io:443/reviews/fusionapp/fusion-index/3#-Jz_7CM0DBOoK3yl5UM3)** ([raw file](https://github.com/fusionapp/fusion-index/blob/82d622b0e015a79f3ed863307d4741b99aed66dd/fusion_index/logging.py#L9)):</sup>
Usually the serialization of complex fields for use by Eliot happens in a serializer close to the logging code (since this is an implementation detail of the logging code itself.) `_ServiceDescription` is a private API so no matter which approach you take you're accidentally exposing this detail. Some ideas:

  1. Interfaces and adapters might help you sweep this detail under a rug, but inventing a new interface (the only one in the project!) doesn't seem great;
  2. Some kind of poor-man's adapter: `fusion_index.logging.asField = methodcaller('asField')`;
  3. Define the Eliot actions in the modules they're intended to be used in and then you don't have to really worry about using private implementation details because the public interface is just the action.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/fusion-index/3)

**Comment by mithrandi** [comment]
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[fusion_index/logging.py, line 9 \[r3\]](https://reviewable.io:443/reviews/fusionapp/fusion-index/3#-Jz_7CM0DBOoK3yl5UM3)** ([raw file](https://github.com/fusionapp/fusion-index/blob/82d622b0e015a79f3ed863307d4741b99aed66dd/fusion_index/logging.py#L9)):</sup>
I moved the logic out of `_ServiceDescription`.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/fusion-index/3)

**Comment by jonathanj** [comment]
Reviewed 4 of 4 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/fusion-index/3)

**Pull request merged**
