### PR TITLE
Add a README with some basic instructions.

### LINKED ISSUE #202: Create README

### PR DESCRIPTION
**Pull request by jonathanj**
Fixes #202.

---
This change is [Reviewable](https://reviewable.io/reviews/fusionapp/fusion-index/203)

### CODE REVIEW

**Comment by mithrandi** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fusionapp/fusion-index/203)*

**Comment by jonathanj** [comment]
bors r+

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fusionapp/fusion-index/203#-:-LG5n5fu3YP5aa3eVj5x:b-ydi9ay)*

**Comment by jonathanj** [comment]
bors r+

---







*Comments from [Reviewable](https://reviewable.io/reviews/fusionapp/fusion-index/203#-:-LG7--dq8vAROX9wYovg:b-ydi9ay)*

**Pull request merged**
